// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ExpenseTracker.Models
{
    public partial class ExpenseTrackerContext : DbContext
    {
        public ExpenseTrackerContext()
        {
        }

        public ExpenseTrackerContext(DbContextOptions<ExpenseTrackerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<LoginInfo> LoginInfos { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }



        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Transaction>(entity =>
            {
                entity.HasOne(d => d.UserPKNavigation)
                    .WithMany(p => p.Transactions)
                    .HasForeignKey(d => d.UserPK)
                    .HasConstraintName("FK_UserPK");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public DbSet<ExpenseTracker.Models.LoginInput> LoginInput { get; set; } = default!;
    }
}