// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTracker.Models
{
    [Index("CategoryId", Name = "IX_Transactions_CategoryId")]
    public partial class Transaction
    {
        [Key]
        public int TransactionId { get; set; }
        public int CategoryId { get; set; }
        public int Amount { get; set; }
        [StringLength(75)]
        public string Note { get; set; }
        public DateTime DateCreated { get; set; }
        public int? UserPK { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Transactions")]
        public virtual Category Category { get; set; }
        [ForeignKey("UserPK")]
        [InverseProperty("Transactions")]
        public virtual LoginInfo UserPKNavigation { get; set; }
    }
}